name: Update snapshots

on:
  schedule:
    - cron: "15 9 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: nixbuild/nix-quick-install-action@v34
    - name: Update emacs snapshot commit
      run: 'nix flake update emacs-snapshot'
    - name: Update commercial snapshot commit
      run: 'nix flake update emacs-snapshot-commercial'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        title: 'Update snapshots'
        body: ''
        commit-message: 'Update snapshots'
        branch: snapshot-update
        branch-suffix: timestamp
        delete-branch: true
        add-paths: flake.lock
